// src/components/AccountAuth.svelte
<script lang="ts">
	import { onMount, onDestroy } from "svelte";
	import { supabase } from "@/integrations/supabase/client";
	import type { User } from "@supabase/supabase-js";
	import { toast } from "svelte-sonner";
	import { LogOut, User as UserIcon } from "lucide-svelte";

	let user: User | null = null;
	let loading = false;
	let email = "";
	let password = "";
	let activeTab = "signin";
	let subscription: { unsubscribe: () => void };

	onMount(() => {
		// Set up auth state listener
		const authListener = supabase.auth.onAuthStateChange((_event, _session) => {
			user = _session?.user ?? null;
		});
		subscription = authListener.data.subscription;

		// Check for existing session
		supabase.auth.getSession().then(({ data: { session: _session } }) => {
			user = _session?.user ?? null;
		});
	});

	onDestroy(() => {
		subscription?.unsubscribe();
	});

	async function signUp(email: string, password: string) {
		const redirectUrl = `${window.location.origin}/`;

		const { error } = await supabase.auth.signUp({
			email,
			password,
			options: {
				emailRedirectTo: redirectUrl,
			},
		});
		return { error };
	}

	async function signIn(email: string, password: string) {
		const { error } = await supabase.auth.signInWithPassword({
			email,
			password,
		});
		return { error };
	}

	async function signOut() {
		const { error } = await supabase.auth.signOut();
		if (error) {
			toast.error("Error signing out: " + error.message);
		} else {
			toast.success("Signed out successfully");
		}
	}

	async function handleSubmit(isSignUp: boolean) {
		if (!email || !password) {
			toast.error("Please fill in all fields");
			return;
		}

		loading = true;
		try {
			const { error } = isSignUp ? await signUp(email, password) : await signIn(email, password);

			if (error) {
				if (error.message.includes("User already registered")) {
					toast.error("This email is already registered. Please sign in instead.");
				} else if (error.message.includes("Invalid login credentials")) {
					toast.error("Invalid email or password. Please check your credentials.");
				} else {
					toast.error(error.message);
				}
			} else {
				if (isSignUp) {
					toast.success("Account created! Please check your email to confirm your account.");
				} else {
					toast.success("Signed in successfully!");
				}
				email = "";
				password = "";
			}
		} catch (error) {
			toast.error("An unexpected error occurred");
		} finally {
			loading = false;
		}
	}
</script>

<div>
	{#if user}
		<div class="message is-primary">
			<div class="message-header">
				<p>
					<span class="icon">
						<UserIcon />
					</span>
					<span>Welcome back!</span>
				</p>
			</div>
			<div class="message-body">
				<p class="mb-2">You're signed in and ready to upload recordings</p>
				<p class="mb-4">
					<strong>{user.email}</strong>
					<br />
					<small>Account created: {new Date(user.created_at).toLocaleDateString()}</small>
				</p>
				<button class="button is-fullwidth" on:click={signOut}>
					<span class="icon">
						<LogOut size={16} />
					</span>
					<span>Sign Out</span>
				</button>
			</div>
		</div>
	{:else}
		<div>
			<h3 class="title is-5">Account (Optional)</h3>
			<p class="subtitle is-6">
				Create an account to manage your uploads, or upload anonymously without signing up
			</p>

			<div class="tabs is-centered">
				<ul>
					<li class:is-active={activeTab === "signin"}>
						<a href="#signin" on:click|preventDefault={() => (activeTab = "signin")}>Sign In</a>
					</li>
					<li class:is-active={activeTab === "signup"}>
						<a href="#signup" on:click|preventDefault={() => (activeTab = "signup")}>Sign Up</a>
					</li>
				</ul>
			</div>

			<form on:submit|preventDefault={() => handleSubmit(activeTab === "signup")}>
				<div class="field">
					<label class="label" for="{activeTab}-email">Email</label>
					<div class="control">
						<input
							id="{activeTab}-email"
							class="input"
							type="email"
							bind:value={email}
							placeholder="Enter your email"
							disabled={loading}
							required
						/>
					</div>
				</div>

				<div class="field">
					<label class="label" for="{activeTab}-password">Password</label>
					<div class="control">
						<input
							id="{activeTab}-password"
							class="input"
							type="password"
							bind:value={password}
							placeholder={activeTab === "signup" ? "Create a password" : "Enter your password"}
							disabled={loading}
							required
						/>
					</div>
				</div>

				<div class="field">
					<div class="control">
						<button
							type="submit"
							class="button is-primary is-fullwidth"
							disabled={loading}
							class:is-loading={loading}
						>
							{activeTab === "signup" ? "Create Account" : "Sign In"}
						</button>
					</div>
				</div>
			</form>
		</div>
	{/if}
</div>

// src/components/AccountAuth.tsx
import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { User, Session } from "@supabase/supabase-js";
import { toast } from "sonner";
import { LogOut, User as UserIcon } from "lucide-react";

export const AccountAuth = () => {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    // Set up auth state listener FIRST
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      (event, session) => {
        setSession(session);
        setUser(session?.user ?? null);
      }
    );

    // THEN check for existing session
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      setUser(session?.user ?? null);
    });

    return () => subscription.unsubscribe();
  }, []);

  const signUp = async (email: string, password: string) => {
    const redirectUrl = `${window.location.origin}/`;
    
    const { error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: redirectUrl
      }
    });
    return { error };
  };

  const signIn = async (email: string, password: string) => {
    const { error } = await supabase.auth.signInWithPassword({
      email,
      password
    });
    return { error };
  };

  const signOut = async () => {
    const { error } = await supabase.auth.signOut();
    if (error) {
      toast.error("Error signing out: " + error.message);
    } else {
      toast.success("Signed out successfully");
    }
  };

  const handleSubmit = async (isSignUp: boolean) => {
    if (!email || !password) {
      toast.error("Please fill in all fields");
      return;
    }

    setLoading(true);
    try {
      const { error } = isSignUp 
        ? await signUp(email, password)
        : await signIn(email, password);

      if (error) {
        if (error.message.includes("User already registered")) {
          toast.error("This email is already registered. Please sign in instead.");
        } else if (error.message.includes("Invalid login credentials")) {
          toast.error("Invalid email or password. Please check your credentials.");
        } else {
          toast.error(error.message);
        }
      } else {
        if (isSignUp) {
          toast.success("Account created! Please check your email to confirm your account.");
        } else {
          toast.success("Signed in successfully!");
        }
        setEmail("");
        setPassword("");
      }
    } catch (error) {
      toast.error("An unexpected error occurred");
    } finally {
      setLoading(false);
    }
  };

  if (user) {
    return (
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <UserIcon className="h-5 w-5 text-primary" />
              </div>
              <div>
                <CardTitle>Welcome back!</CardTitle>
                <CardDescription>You're signed in and ready to upload recordings</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
              <div>
                <p className="font-medium text-foreground">{user.email}</p>
                <p className="text-sm text-muted-foreground">
                  Account created: {new Date(user.created_at).toLocaleDateString()}
                </p>
              </div>
            </div>
            <Button 
              onClick={signOut} 
              variant="outline" 
              className="w-full"
            >
              <LogOut className="h-4 w-4 mr-2" />
              Sign Out
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Account</CardTitle>
          <CardDescription>
            Sign in to your account or create a new one to upload recordings
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="signin" className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="signin">Sign In</TabsTrigger>
              <TabsTrigger value="signup">Sign Up</TabsTrigger>
            </TabsList>

            <TabsContent value="signin" className="space-y-4 mt-6">
              <div className="space-y-2">
                <Label htmlFor="signin-email">Email</Label>
                <Input
                  id="signin-email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  disabled={loading}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="signin-password">Password</Label>
                <Input
                  id="signin-password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Enter your password"
                  disabled={loading}
                />
              </div>
              <Button 
                onClick={() => handleSubmit(false)} 
                className="w-full"
                disabled={loading}
              >
                {loading ? "Signing In..." : "Sign In"}
              </Button>
            </TabsContent>

            <TabsContent value="signup" className="space-y-4 mt-6">
              <div className="space-y-2">
                <Label htmlFor="signup-email">Email</Label>
                <Input
                  id="signup-email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  disabled={loading}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="signup-password">Password</Label>
                <Input
                  id="signup-password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Create a password"
                  disabled={loading}
                />
              </div>
              <Button 
                onClick={() => handleSubmit(true)} 
                className="w-full"
                disabled={loading}
              >
                {loading ? "Creating Account..." : "Create Account"}
              </Button>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
};
